### ISSUE TITLE
github action for automatic python package upload

### ISSUE THREAD

**Issue by codePerfectPlus** [Py-Contributors/audiobook#3]
create a complete GitHub action to upload python package on PyPI.org

**Comment by JoeAmedeo** [comment]
I would be willing to pick this one up. Would just like to ask how would you like the trigger to be set up?

**Comment by codePerfectPlus** [comment]
Triggered when code is pushed to the repository or you have some good idea. I am not good with GitHub actions

**Comment by JoeAmedeo** [comment]
Most of the times I've seen it implemented based on tag releases. If you want to go the extra step you can find a means to automate creating the tag releases based on changing the to the setup file, or based on the commit messages to bump the semver. I have an implementation ready for basic tag releases ready, and can post that PR once this issue is assigned to me.
